[package]
name = "login_enum_option"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
auth_enum_option = { path = "../auth_enum_option" }
